[tool.isort]
profile = "black"

[tool.ruff]
line-length = 120
target-version = "py39"

[tool.ruff.lint]
ignore = ["F401"]

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.pylint.format]
max-line-length = "120"
max-locals = 45
max-args = 20
max-branches = 30
max-statements = 90

disable = """
    missing-module-docstring,
    duplicate-code,
    too-few-public-methods,
    invalid-name,
    too-many-instance-attributes,
    too-many-ancestors,
    not-callable,
    use-implicit-booleaness-not-comparison,
    implicit-str-concat,
    inconsistent-return-statements,
"""